{% set name = "rnaiutilities"  %}
{% set version = "0.1.0" %}

package:
  name: "{{ name }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/cbg-ethz/rnaiutilities/archive/v{{ version }}.tar.gz
  sha256: e82e78aa2310062fde1134584de69d3b930244a19a3da909ad7965b622cea284

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python
    - click >=6.7
    - h5py >=2.7.0
    - numpy >=1.11.0
    - pandas >=0.20.1
    - psycopg2 >=2.7.1
    - pytest >=3.0.5
    - pyyaml >=3.12
    - scipy >=0.19.0
    - nose ==1.3.7
    - sphinx >=1.4.5

test:
  imports:
    - rnaiutilities

about:
  home: https://github.com/cbg-ethz/rnaiutilities
  license: GNU General Public License v3 (GPLv3)
  license_file: LICENSE
  summary: 'A collection of commandline tools and python modules for working with image-based RNAi screens.'
  doc_url: https://rnaiutilities.readthedocs.io/en/latest/
  dev_url: https://github.com/cbg-ethz/rnaiutilities
