language: python

sudo: required
cache: packages

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov
  - pip install tox-travis

script:
  - rnai-query query --help
  - rnai-parse parse --help

after_success:
  - py.test --cov=./
  - codecov

