language: python

sudo: required
cache: packages

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov
  - pip install tox-travis

script:
  - tox

after_success:
  - codecov

