language: python

sudo: false

cache: packages

os:
  - linux
  - osx

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov

script:
  - rnai-query query --help
  - rnai-parse parsereport --help
  - py.test --cov=./

after_success:
  - codecov

